language: go

sudo: false

go:  
  - "1.9"
  - "1.10"
  - "1.11"
  - tip

matrix:
  allow_failures:
    - go: 'tip'
  include:
    - go: "1.11.x"
      script: go test -v -mod=vendor ./...

env:
  - GO111MODULE=on